config/routes.rb
Validate::Application.routes.draw do
  get "welcome/index"
  get "welcome/check"
  get "welcome/facebook_acc"
  get "welcome/delete_post"
  
  root :to => "welcome#index"

  resources :users

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match '/create', to: 'welcome#create', via: 'post'
  match "/welcome/check" , to: 'welcome#check', via: 'post'
  match "/welcome/checkavailable" , to: 'welcome#checkavailable', via: 'post'
  match '/logout' => 'welcome#destroy', as: :logout
  match '/micropost', to: 'welcome#micropost', via: 'post'

  get '/acc', to: 'welcome#facebook_acc', as: 'welcome_facebook_acc'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :phonenumber, :username

  devise :omniauthable, :omniauth_providers => [:facebook]
  def self.from_omniauth(auth)
    oauth = Koala::Facebook::OAuth.new("1533721856892334","d5c1a63a5b804841e87813a641416fdd")
    new_access_info = oauth.exchange_access_token_info auth.credentials.token
    new_access_token = new_access_info["access_token"]
    
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
      user.oauth_token = new_access_token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include WelcomeHelper
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      login(@user)
      redirect_to welcome_facebook_acc_path, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      url = "https://www.facebook.com/"
      redirect_to url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def check
    @username = User.find_by_username(params[:username])
    respond_to do |format|
      format.json { render :json => !@username }
    end
  end

  def checkavailable
    phonenumber = params[:phonenumber]
    email = params[:email]
    if phonenumber == ""
      phone = nil
    mail = email
    elsif email == ""
      mail = nil
    phone = phonenumber
    else
    mail = email
    phone = phonenumber
    end
    @acc = User.find_by_email_and_phonenumber(mail,phone)
    respond_to do |format|
      format.json { render :json => !@acc, status: :ok }
    end
  end

  def create
    @user = User.create(:username => params[:username], :password => params[:password],
                        :email => params[:email], :phonenumber => params[:phonenumber])
    if @user
      sleep(4.0)
      redirect_to root_path
    else
    end
  end

  def destroy
    logout
    redirect_to root_url
  end

  def facebook_acc
    @graph = Koala::Facebook::GraphAPI.new(current_user.oauth_token)
    profile = @graph.get_object("me")
    @friends = @graph.get_connections("me", "taggable_friends?fields=id,name,picture.type(large)")
    @feeds = @graph.get_connections("me", "feed?fields=message&limit=2")
    logger.debug "friends #{@photo}"
  end

  def micropost
    @graph = Koala::Facebook::GraphAPI.new(current_user.oauth_token)
    @graph.put_connections("me", "feed", :message => params[:micropost])
    redirect_to welcome_facebook_acc_path
  end

  def delete_post
    @graph = Koala::Facebook::GraphAPI.new(current_user.oauth_token)
    @ids = params[:ids]
    @graph.delete_object(params[:ids])
    redirect_to welcome_facebook_acc_path
  end
  
  def image
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def login(user)
    session[:user_id] = user.id
  end
  def current_user
    current_user = User.find(session[:user_id]) if session[:user_id]
  end
  def logout
    session[:user_id] = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
		<%= stylesheet_link_tag    "application" %>
		<%= stylesheet_link_tag    "foundation-icons" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>

	</head>
	<body class="background">
		<%= yield %>
	</body>
</html>

app/views/welcome/facebook_acc.html.erb
<div class="medium-4 medium-centered row" align="center">
	<div class="medium-8 medium-centered columns" id="friends">
		<%= current_user.provider %>
		<br />
		<%= current_user.uid %>
		<br />
		<%= link_to "Sign out", logout_path %>
	</div>
	<div class="medium-10 medium-centered columns">
		<%= form_tag(micropost_path) do %>
		<fieldset id="friends" align="left">
			<legend>
				Post
			</legend>
			<%= text_area_tag :micropost%>
			<% if @feeds%>
			<% @feeds.each do |u|%>
			<fieldset style="padding: 5px" >
				<legend>
					<% if u['created_time'] != nil%>
					<%= u['created_time'].to_date.strftime("%y/%m/%d")%>
					<%end%>
					(<%= link_to "delete", {:controller => "welcome", :action => "delete_post", :ids => u['id']} %>)
				</legend>
				<p style="word-break: break-all">
					<%= u['message']%>
					</p>
			</fieldset>
			<%end%>
			<%end%>
		</fieldset>
		<%= submit_tag("Post",class: "button [tiny small large]") %>
		<%end%>
	</div>
</div>
<div class="medium-4 medium-centered row" align="left" >
	<div class="medium-12 medium-centered columns" id="friends">
		<h4><i class="step fi-results-demographics size-50">&nbspFriends List</i></h4>
		<% if @friends%>
		<% @friends.each do |u|%>
		<img src="<%= u['picture']['data']['url']%>" width="30px" height="30px" />
		<%= u['name']%>
		<br />
		<%end%>
		<%end%>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="medium-4 medium-centered row" align="center">
	<div class="medium-12 medium-centered columns" id="Sign">
		<h2><i class="step fi-social-twitter size-60" id="valid">&nbspSign up</i></h2>	
		<div id="hideMsg" style="display: none">
			Redirect in <span>5</span> seconds
		</div>
	</div>
	<div class="medium-8 medium-centered columns">
		<%= form_tag(create_path, :id => "check") do %>
		Username
		<br />
		<%= text_field_tag 'username', nil, :class => 'username inputbox'%>
		Password
		<br />
		<%= password_field_tag 'password', nil, :class => 'password inputbox'%>
		Email
		<br />
		<%= text_field_tag 'email', nil, :class => 'email inputbox'%>
		Phonenumber
		<br />
		<%= text_field_tag 'phonenumber', nil, :class => 'phonenumber inputbox'%>
		<%= submit_tag("Sign",
		class: "button [tiny small large]", :id => "button")%>
		<%= link_to "Login with Facebook", user_omniauth_authorize_path(:facebook), :class => "popup", :"data-width" => 500, :"data-height" => 200 %>
		<%end%>
	</div>
</div>